# Generated by Django 4.1.2 on 2022-10-21 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumuser',
            name='Puesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.puesto'),
        ),
    ]
