# Generated by Django 4.1.2 on 2022-10-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField(max_length=300)),
                ('FechaElaboracion', models.DateTimeField(auto_now_add=True)),
                ('Hecho', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clave_Tecnologico', models.CharField(max_length=3)),
                ('Nombre', models.CharField(max_length=50)),
                ('Ciudad', models.CharField(max_length=30)),
            ],
        ),
    ]
